name: Test Workflow Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World! Testing GitHub for Google Chat notifications."
